spring:
  application:
    name: users
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_URL:postgres}?createSchema=true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

application:
  open-api:
    email: ${spring.mail.sender.email}
    server:  http://127.0.0.1:8222

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: mmf-ask-app
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 8222