global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'users-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.149.75:8222']
        labels:
          application: movies-api